# Generated by Django 3.1.1 on 2021-02-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EveNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_id', models.IntegerField()),
                ('eve_name', models.CharField(max_length=500)),
                ('eve_catagory', models.CharField(choices=[
                 ('alliance', 'alliance'), ('character', 'character'), ('corporation', 'corporation')], max_length=30)),
                ('blacklisted', models.BooleanField(default=False)),
                ('restricted', models.BooleanField(default=False)),
                ('added_by', models.CharField(max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('corporation_id', models.IntegerField(default=None, null=True)),
                ('corporation_name', models.CharField(default=None, max_length=500, null=True)),
                ('alliance_id', models.IntegerField(default=None, null=True)),
                ('alliance_name', models.CharField(default=None, max_length=500, null=True)),
            ],
            options={
                'permissions': (('view_basic_eve_notes', 'Can View own corps notes'), ('view_eve_blacklist', 'Can View the Blacklist'), ('view_eve_notes', 'Can view all eve notes'), ('add_basic_eve_notes', 'Can Add own corp members to notes'), ('add_new_eve_notes', 'Can add new eve notes'), ('add_to_blacklist', 'Can add to Blacklist'), ('view_restricted_eve_notes', 'Can View restricted eve notes'), ('add_restricted_eve_notes', 'Can Add restricted eve notes')),
            },
        ),
        migrations.CreateModel(
            name='EveNoteComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_by', models.CharField(max_length=500)),
                ('comment', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('restricted', models.BooleanField(default=False)),
                ('eve_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='comment', to='blacklist.evenote')),
            ],
            options={
                'permissions': (('view_eve_note_comments', 'Can view eve note comments'), ('view_eve_note_restricted_comments', 'Can view restricted eve note comments'), ('add_new_eve_note_comments', 'Can add comments on eve notes'), ('add_new_eve_note_restricted_comments', 'Can add new restricted comments to eve notes')),
            },
        ),
    ]
