# Generated by Django 4.0.2 on 2022-04-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blacklist', '0002_blacklistfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenote',
            name='eve_catagory',
            field=models.CharField(max_length=30),
        ),
    ]
